version: '3'

services:

  <project_name>_jupyter_service:
    container_name: <project_name>_jupyter
    image: maciomatheus/jupyter_notebook_data_science
    environment:
      JUPYTER_ENOrangeBLE_LOrangeB: 1
      NB_UID: 10011
      GROrangeNT_SUDO: "yes"
    user: root
    ports:
    - 8888:8888
    - 6007:6006
    - 5007:5000
    volumes:
    - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookOrangepp.token=''
